### ISSUE TITLE
Effect Of  Library On UI

### ISSUE THREAD

**Issue by Faizan-Khurshid** [Expertizo/react-fb-image-grid#1]
when I tried to use(import) the the library it effect my UI my very badly.

**Note** : **I am using bootstrap library for the UI**

**this is the output without importing the library**

![wihtoutlibrary](https://user-images.githubusercontent.com/32761668/46382435-611d4d00-c6c4-11e8-8cad-06c35e0ce0fa.JPG)

 **this is the output after importing library**

![withlibrary](https://user-images.githubusercontent.com/32761668/46382478-94f87280-c6c4-11e8-865e-b5ea99b87414.JPG)

**Comment by kashifsulaiman** [comment]
@faizi23 please let me know if you're using any library for the styling purpose!

**Comment by ManalLiaquat** [comment]
> when I tried to use(import) the the library it effect my UI my very badly.
> 
> **Note** : **I am using bootstrap library for the UI**
> 
> **this is the output without importing the library**
> 
> ![wihtoutlibrary](https://user-images.githubusercontent.com/32761668/46382435-611d4d00-c6c4-11e8-8cad-06c35e0ce0fa.JPG)
> 
> **this is the output after importing library**
> 
> ![withlibrary](https://user-images.githubusercontent.com/32761668/46382478-94f87280-c6c4-11e8-865e-b5ea99b87414.JPG)

I am facing the **exact same problem**

**Comment by Faizan-Khurshid** [comment]
@kashifsulaiman I am using bootsrap 4 library

**Comment by kashifsulaiman** [comment]
@faizi23 @ManalLiaquat use `react-bootstrap` instead and let me know please! Because this library also uses the same package!

**Comment by ManalLiaquat** [comment]
### Please reopen this issue

according to [this](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github), I cannot **reopen** my issues on other's _repo_.

@kashifsulaiman Please **reopen** this [issue](https://github.com/Expertizo/react-fb-image-grid/issues/2#issuecomment-427389026) because it is not resolved yet.

**Comment by Faizan-Khurshid** [comment]
@kashifsulaiman  I tried using react-strap but got the same result
Also I didn't install react-strap library.I used your library in which react-strap is already included but got the same result
here is my package.json in which bootsrap and react-strap are uninstalled
![capture](https://user-images.githubusercontent.com/32761668/46583394-9f718e00-ca6f-11e8-8082-d22ac1c61198.JPG)

**Comment by kashifsulaiman** [comment]
@faizi23 it's not react-strap, it's `react-bootstrap`! See the react-bootstrap guide for using layout! You'll definitely find a way how to use this library!

**Comment by imma0010** [comment]
Sorry to say this but I am also getting the same problem while importing a variable from library to my code.

Without import:
![problem1](https://user-images.githubusercontent.com/42366055/75111244-d85bd400-565f-11ea-8c8e-e3e2661a555c.PNG)

With import:
![problem2](https://user-images.githubusercontent.com/42366055/75111266-07724580-5660-11ea-8a85-8cb05c93262c.PNG)

I am using Material-UI.
