### ISSUE TITLE
conflict with bootstrap button and modal (I use reactstrap).

### ISSUE THREAD

**Issue by pdexx** [Expertizo/react-fb-image-grid#14]
It's awesome, but conflict with bootstrap button and modal (I use reactstrap).

**Comment by kashifsulaiman** [comment]
@pdexx Thanks, could you please let me know the reactstrap version? and a screenshot

**Comment by pdexx** [comment]
"reactstrap": "^8.0.0" 
The button style become default style instead of bootstrap style, and the window of modal don't 
appear when you trigger. However, the react-fb-image-grid working normally. Sorry I don't save a screenshot, and thank you for your reply.

**Comment by kashifsulaiman** [comment]
@pdexx yeah since this library is dependent on React Bootstrap, so the css might conflict of reactstrap library with it. So I recommend you to if you're using this library, go for React Bootstrap then!

**Comment by pdexx** [comment]
Ok, Thank you very much.
