### ISSUE TITLE
Iteration Key Error

### ISSUE THREAD

**Issue by UmarBaraq** [Expertizo/react-fb-image-grid#5]
Getting each child should have an own key in iteration warning.
Even if I'm using library alone without any other code.

**Comment by ManalLiaquat** [comment]
> Getting each child should have an own key in iteration warning.
> Even if I'm using library alone without any other code.

because the author didn't use the **key** attribute in mapping the images

**Comment by muhammadsarim555** [comment]
this is not your fault this is library author mistake who did not use index in map mathod

**Comment by Ovi** [comment]
It's just a warning. So you can ignore it for now.

**Comment by kashifsulaiman** [comment]
@UmarBaraq Thanks for the issue! It'll be fixed in the next version. v0.1.3

**Comment by kashifsulaiman** [comment]
https://github.com/Expertizo/react-fb-image-grid/pull/6
Fixed this issue.

Closing this issue, feel free to reopen if you find the issue again in `v0.1.3`

**Comment by tannguyenit** [comment]
[evidence image.](https://ibb.co/bFaxNq)
In version 0.1.4 I get this error. `react.development.js:207 Warning: Each child in an array or iterator should have a unique "key" prop` Please resolve this error to me

**Comment by kashifsulaiman** [comment]
@tannguyenit fixed this issue in https://github.com/Expertizo/react-fb-image-grid/pull/9/. Merged as well,
Checkout v0.1.5
