### ISSUE TITLE
Responsiveness Issue

### ISSUE THREAD

**Issue by yaqoobakbar** [Expertizo/react-fb-image-grid#7]
The library has issues in responsiveness with respect to zoom-in / zoom-out / changing width of the page inside the browser, the component/library doesn't respond to the  page width while zooming in or out.

tried on Google Chrome
Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by yaqoobakbar** [comment]
Performed tests on the following file(s):
Some bugs are present in the es/css/style.css file

Making changes in the following code has no effect on the UI:
.height-one {
  height: 100vw;
}

.height-two {
  height: 50vw;
}

.height-three {
  height: 33vw;
}

The height dimensions are hard coded into the /es/component/Images.js file

**Comment by kashifsulaiman** [comment]
@yaqoobakbar Fixed these bugs in `v0.1.4`
PR: https://github.com/Expertizo/react-fb-image-grid/pull/8
